app:
  port: 3030
postgres:
  type: postgres
  host: ep-dark-fog-a5e81ezy.us-east-2.aws.neon.tech
  port: 5432
  database: test-tg-bot
  username: test-tg-bot_owner
  password: jb75kJHNZzPd
  synchronize: true
  ssl: true
  applicationName: test-tg-bot
bot:
  token: 669334747:AAEdl9W7QJFXW7T3q5Y085mwK22_XuMMI9U
