app:
  port: 3000
postgres:
  type: postgres
  host: localhost
  port: 5433
  database: test-tg-bot
  username: postgres
  password: postgres
  synchronize: true
  applicationName: test-tg-bot
bot:
  token: 669334747:AAEdl9W7QJFXW7T3q5Y085mwK22_XuMMI9U
